<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="WRITE_PROTECTED_USINT" Id="{f1079ab8-dc5a-06e1-34a2-495bc4f858b4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WRITE_PROTECTED_USINT
VAR_INPUT
    Ptr : POINTER TO USINT;
    Value : USINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[Ptr^ := Value;]]></ST>
    </Implementation>
    <LineIds Name="WRITE_PROTECTED_USINT">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>