<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="WRITE_PROTECTED_WORD" Id="{7958aecd-9f81-09a2-1a35-bb6dd127121b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION WRITE_PROTECTED_WORD
VAR_INPUT
    Ptr : POINTER TO WORD;
    Value : WORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[Ptr^ := Value;]]></ST>
    </Implementation>
    <LineIds Name="WRITE_PROTECTED_WORD">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>